#+TITLE: My configs sharing setup

* Intro
  Working with many computers justify the work to setup a mechanism to share
  some configurations would be common between them, i.e, shell startup files,
  editor, IDE or any other software customization, secrets files, etc.

  Many people solve this problem with a cloud storage provider, like Dropbox or
  Github, and the decision between one or another in the end is personal.

  It is almost a norm to see repositories in Github called dotfiles or something
  like that. And the first result for searching for that word gave me a great
  article about this [[https://zachholman.com/2010/08/dotfiles-are-meant-to-be-forked/][Dotfiles are meant to be forked]].

  I have a more rudimentary mechanism than that or any other of those great
  systems out there, implying manual tweaks, but I'm happy with it, and I'm
  documenting it here just to don't get lost when installing my next brand new
  computer.

  With this setup, I achieve:

  - Sharing among my computers
  - Backup the files
  - Share some of them to the public

* My setup

  I'm using as a cloud storage mainly Dropbox and for some specific files,
  Github.

  I found it convenient the automatic synchronization Dropbox provides, so I
  don't have to remember to /update/ the machines manually.

  Over Dropbox, just for my /scripts/ folder I'm using a Git repository I share
  in Github. It is there to make a proper software change control on those files
  that have some (almost zero, but some) probability to be modified by a 3rd
  person.

  For the rest of the files, I just try to categorize the files in appropriate
  folders. And is that categorization what is more important for me to document
  than anything else about the mechanism.

** Directory structure

   - <DF> (Dropbox Folder)
     - profiles
       - commons
         - scripts (git repository shared at GitHub)
         - confs
           - bashrc
           - spacemacs
           - bash.d
             - module_1
             - . . .
             - module_n
       - instances
         - machine_1
           - scripts -> <DF>/profiles/commons/scripts
           - confs
             - bashrc -> <DF>/profiles/commons/confs/bashrc
             - spacemacs -> <DF>/profiles/commons/confs/spacemacs
             - bash.d
               - module_1 -> <DF>/profiles/commons/confs/bash.d/module_1
               - module_3 -> <DF>/profiles/commons/confs/bash.d/module_3
         - machine_2
           - scripts -> <DF>/profiles/commons/scripts
           - confs
             - bashrc -> <DF>/profiles/commons/confs/bashrc
             - spacemacs -> <DF>/profiles/commons/confs/spacemacs
             - bash.d
               - module_2 -> <DF>/profiles/commons/confs/bash.d/module_2
               - module_3 -> <DF>/profiles/commons/confs/bash.d/module_3
               - module_4 -> <DF>/profiles/commons/confs/bash.d/module_4
